FROM node:24-alpine AS build
WORKDIR /app

ARG VITE_SITE_NAME=ThoughtFlow
ENV VITE_SITE_NAME=$VITE_SITE_NAME

COPY package*.json ./
RUN npm ci

COPY . ./
RUN npm run build

FROM nginx:1.29-alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
